/**
 * MySQL to PostgreSQL-compatible normalization.
 * Transforms MySQL DDL into PG-style DDL so the DSQL converter can process it.
 */

export function normalizeMysql(sql, changes) {
    let result = sql;

    result = removeDelimiters(result, changes);
    result = convertBackticks(result, changes);
    result = removeEngineCharset(result, changes);
    result = convertAutoIncrement(result, changes);
    result = convertUnsignedTypes(result, changes);
    result = convertMysqlTypes(result, changes);
    result = convertEnums(result, changes);
    result = convertSetType(result, changes);
    result = removeZerofill(result, changes);
    result = removeOnUpdate(result, changes);
    result = removeFulltextSpatialIndexes(result, changes);
    result = convertInlineKeys(result, changes);
    result = removeMysqlProcedures(result, changes);
    result = removeMysqlComments(result, changes);

    return result;
}

function removeDelimiters(sql, changes) {
    const delimiterRegex = /DELIMITER\s+(\S+)[\s\S]*?DELIMITER\s*;/gi;
    const matches = sql.match(delimiterRegex);
    if (matches) {
        changes.push({ type: 'removed', message: `Removed ${matches.length} DELIMITER block(s) — stored procedures/functions not supported in DSQL` });
        sql = sql.replace(delimiterRegex, '');
    }
    const strayDelimiter = /^DELIMITER\s+\S+\s*$/gim;
    sql = sql.replace(strayDelimiter, '');
    return sql;
}

function convertBackticks(sql, changes) {
    if (/`/.test(sql)) {
        changes.push({ type: 'modified', message: 'Converted backtick-quoted identifiers to double-quoted identifiers' });
        sql = sql.replace(/`([^`]+)`/g, '"$1"');
    }
    return sql;
}

function removeEngineCharset(sql, changes) {
    const patterns = [
        /\s*ENGINE\s*=\s*\w+/gi,
        /\s*(?:DEFAULT\s+)?(?:CHARACTER\s+SET|CHARSET)\s*=?\s*\w+/gi,
        /\s*(?:DEFAULT\s+)?COLLATE\s*=?\s*[\w_]+/gi,
        /\s*AUTO_INCREMENT\s*=\s*\d+/gi,
        /\s*ROW_FORMAT\s*=\s*\w+/gi,
    ];

    let removed = false;
    patterns.forEach(regex => {
        if (sql.match(regex)) {
            removed = true;
            sql = sql.replace(regex, '');
        }
    });

    if (removed) {
        changes.push({ type: 'removed', message: 'Removed ENGINE, CHARACTER SET, COLLATE, ROW_FORMAT clauses' });
    }

    const colCharset = /\s+CHARACTER\s+SET\s+\w+(?:\s+COLLATE\s+[\w_]+)?/gi;
    sql = sql.replace(colCharset, '');

    return sql;
}

function convertAutoIncrement(sql, changes) {
    const regex = /(\w+)\s+((?:TINY|SMALL|MEDIUM|BIG)?INT(?:EGER)?)\s*(?:\(\d+\))?\s*(?:UNSIGNED\s+)?(?:NOT\s+NULL\s+)?AUTO_INCREMENT/gi;
    const matches = sql.match(regex);
    if (matches) {
        changes.push({ type: 'modified', message: `Converted ${matches.length} AUTO_INCREMENT column(s) to GENERATED BY DEFAULT AS IDENTITY` });
    }

    sql = sql.replace(
        /(\w+)\s+(BIGINT)\s*(?:\(\d+\))?\s*(?:UNSIGNED\s+)?(?:NOT\s+NULL\s+)?AUTO_INCREMENT/gi,
        '$1 BIGINT GENERATED BY DEFAULT AS IDENTITY (CACHE 1)'
    );
    sql = sql.replace(
        /(\w+)\s+((?:MEDIUM|SMALL|TINY)?INT(?:EGER)?)\s*(?:\(\d+\))?\s*(?:UNSIGNED\s+)?(?:NOT\s+NULL\s+)?AUTO_INCREMENT/gi,
        '$1 INTEGER GENERATED BY DEFAULT AS IDENTITY (CACHE 1)'
    );

    return sql;
}

function convertUnsignedTypes(sql, changes) {
    if (sql.match(/\bUNSIGNED\b/gi)) {
        changes.push({ type: 'warning', message: 'Removed UNSIGNED qualifiers — DSQL (PostgreSQL) does not support unsigned integer types' });
        sql = sql.replace(/\bUNSIGNED\b/gi, '');
    }
    return sql;
}

function convertMysqlTypes(sql, changes) {
    const mappings = [
        [/\bTINYINT\(1\)/gi, 'BOOLEAN'],
        [/\bTINYINT(?:\(\d+\))?/gi, 'SMALLINT'],
        [/\bMEDIUMINT(?:\(\d+\))?/gi, 'INTEGER'],
        [/\bINT\(\d+\)/gi, 'INTEGER'],
        [/\bBIGINT\(\d+\)/gi, 'BIGINT'],
        [/\bDOUBLE(?:\s+PRECISION)?(?:\(\d+,\s*\d+\))?/gi, 'DOUBLE PRECISION'],
        [/\bFLOAT\(\d+,\s*\d+\)/gi, 'REAL'],
        [/\bDATETIME(?:\(\d+\))?/gi, 'TIMESTAMP'],
        [/\bLONGTEXT/gi, 'TEXT'],
        [/\bMEDIUMTEXT/gi, 'TEXT'],
        [/\bTINYTEXT/gi, 'TEXT'],
        [/\bLONGBLOB/gi, 'BYTEA'],
        [/\bMEDIUMBLOB/gi, 'BYTEA'],
        [/\bTINYBLOB/gi, 'BYTEA'],
        [/\bBLOB\b/gi, 'BYTEA'],
        [/\bVARBINARY\(\d+\)/gi, 'BYTEA'],
        [/\bBINARY\(\d+\)/gi, 'BYTEA'],
    ];

    let converted = false;
    mappings.forEach(([regex, replacement]) => {
        if (sql.match(regex)) {
            converted = true;
            sql = sql.replace(regex, replacement);
        }
    });

    if (converted) {
        changes.push({ type: 'modified', message: 'Converted MySQL data types to PostgreSQL equivalents' });
    }
    return sql;
}

function convertEnums(sql, changes) {
    const enumRegex = /\bENUM\s*\(([^)]+)\)/gi;
    const matches = sql.match(enumRegex);
    if (matches) {
        changes.push({ type: 'modified', message: `Converted ${matches.length} ENUM column(s) to VARCHAR with CHECK constraint note` });
        sql = sql.replace(enumRegex, 'VARCHAR(255) /* ENUM values: $1 */');
    }
    return sql;
}

function convertSetType(sql, changes) {
    const setRegex = /\bSET\s*\(([^)]+)\)/gi;
    const matches = sql.match(setRegex);
    if (matches) {
        changes.push({ type: 'modified', message: `Converted ${matches.length} SET column(s) to VARCHAR(255) — implement set logic in application` });
        sql = sql.replace(setRegex, 'VARCHAR(255) /* SET values: $1 */');
    }
    return sql;
}

function removeZerofill(sql, changes) {
    if (sql.match(/\bZEROFILL\b/gi)) {
        changes.push({ type: 'removed', message: 'Removed ZEROFILL — not supported in PostgreSQL/DSQL' });
        sql = sql.replace(/\bZEROFILL\b/gi, '');
    }
    return sql;
}

function removeOnUpdate(sql, changes) {
    const regex = /\s+ON\s+UPDATE\s+(?:CURRENT_TIMESTAMP|NOW\(\))(?:\(\d+\))?/gi;
    if (sql.match(regex)) {
        changes.push({ type: 'removed', message: 'Removed ON UPDATE CURRENT_TIMESTAMP — use application logic instead' });
        sql = sql.replace(regex, '');
    }
    return sql;
}

function removeFulltextSpatialIndexes(sql, changes) {
    const inlineRegex = /,?[ \t]*\n?[ \t]*(?:FULLTEXT|SPATIAL)\s+(?:KEY|INDEX)\s+[\w"]*\s*\([^)]+\)/gi;
    const matches = sql.match(inlineRegex);
    if (matches) {
        changes.push({ type: 'removed', message: `Removed ${matches.length} FULLTEXT/SPATIAL index(es) — not supported in DSQL` });
        sql = sql.replace(inlineRegex, '');
    }

    const standaloneRegex = /CREATE\s+(?:FULLTEXT|SPATIAL)\s+INDEX\s+[\w"]+\s+ON\s+[\w."]+\s*\([^)]+\)[^;]*;/gi;
    const standaloneMatches = sql.match(standaloneRegex);
    if (standaloneMatches) {
        changes.push({ type: 'removed', message: `Removed ${standaloneMatches.length} standalone FULLTEXT/SPATIAL index(es)` });
        sql = sql.replace(standaloneRegex, '');
    }

    return sql;
}

function convertInlineKeys(sql, changes) {
    const keyRegex = /,?[ \t]*\n?[ \t]*(?:UNIQUE\s+)?KEY\s+[\w"]+\s*\([^)]+\)/gi;
    const matches = sql.match(keyRegex);
    if (matches) {
        changes.push({ type: 'removed', message: `Removed ${matches.length} inline KEY declaration(s) — converted tables will use CREATE INDEX ASYNC separately` });
        sql = sql.replace(keyRegex, '');
    }
    return sql;
}

function removeMysqlProcedures(sql, changes) {
    const procRegex = /CREATE\s+(?:DEFINER\s*=\s*\S+\s+)?(?:PROCEDURE|FUNCTION)\s+([\w"]+)\s*\([^)]*\)[^]*?(?:BEGIN[^]*?END)\s*;?/gi;
    const matches = sql.match(procRegex);
    if (matches) {
        matches.forEach(m => {
            const name = m.match(/(?:PROCEDURE|FUNCTION)\s+([\w"]+)/i);
            changes.push({ type: 'removed', message: `Removed stored ${m.match(/PROCEDURE/i) ? 'procedure' : 'function'} "${name ? name[1] : 'unknown'}" — not supported in DSQL` });
        });
        sql = sql.replace(procRegex, '');
    }
    return sql;
}

function removeMysqlComments(sql, changes) {
    const commentRegex = /\s+COMMENT\s+'(?:[^']|'')*'/gi;
    if (sql.match(commentRegex)) {
        sql = sql.replace(commentRegex, '');
    }
    return sql;
}
