/**
 * SQL Server (T-SQL) to PostgreSQL-compatible normalization.
 * Transforms T-SQL DDL into PG-style DDL so the DSQL converter can process it.
 */

export function normalizeSqlServer(sql, changes) {
    let result = sql;

    result = removeGoStatements(result, changes);
    result = removeSetStatements(result, changes);
    result = removeBracketQuotes(result, changes);
    result = convertIdentity(result, changes);
    result = convertSqlServerTypes(result, changes);
    result = removeClusteredKeywords(result, changes);
    result = removeFilegroups(result, changes);
    result = removeWithOptions(result, changes);
    result = removeTsqlProcedures(result, changes);
    result = convertGetdate(result, changes);
    result = convertIsnull(result, changes);
    result = removeSchemaBinding(result, changes);

    return result;
}

function removeGoStatements(sql, changes) {
    const regex = /^\s*GO\s*$/gim;
    if (regex.test(sql)) {
        changes.push({ type: 'removed', message: 'Removed GO batch separators' });
        sql = sql.replace(regex, '');
    }
    return sql;
}

function removeSetStatements(sql, changes) {
    const regex = /^\s*SET\s+(?:ANSI_NULLS|ANSI_PADDING|QUOTED_IDENTIFIER|NOCOUNT|XACT_ABORT)\s+(?:ON|OFF)\s*;?\s*$/gim;
    const matches = sql.match(regex);
    if (matches) {
        changes.push({ type: 'removed', message: `Removed ${matches.length} T-SQL SET statement(s)` });
        sql = sql.replace(regex, '');
    }
    return sql;
}

function removeBracketQuotes(sql, changes) {
    if (/\[/.test(sql)) {
        changes.push({ type: 'modified', message: 'Converted bracket-quoted identifiers [name] to double-quoted "name"' });
        sql = sql.replace(/\[([^\]]+)\]/g, '"$1"');
    }
    return sql;
}

function convertIdentity(sql, changes) {
    const regex = /([\w"]+)\s+((?:BIG)?INT(?:EGER)?)\s+IDENTITY\s*(?:\(\s*\d+\s*,\s*\d+\s*\))?/gi;
    const matches = sql.match(regex);
    if (matches) {
        changes.push({ type: 'modified', message: `Converted ${matches.length} IDENTITY column(s) to GENERATED BY DEFAULT AS IDENTITY` });
    }

    sql = sql.replace(
        /([\w"]+)\s+(BIGINT)\s+IDENTITY\s*(?:\(\s*\d+\s*,\s*\d+\s*\))?/gi,
        '$1 BIGINT GENERATED BY DEFAULT AS IDENTITY (CACHE 1)'
    );
    sql = sql.replace(
        /([\w"]+)\s+(INT(?:EGER)?)\s+IDENTITY\s*(?:\(\s*\d+\s*,\s*\d+\s*\))?/gi,
        '$1 INTEGER GENERATED BY DEFAULT AS IDENTITY (CACHE 1)'
    );

    return sql;
}

function convertSqlServerTypes(sql, changes) {
    const mappings = [
        [/\bNVARCHAR\s*\(MAX\)/gi, 'TEXT'],
        [/\bVARCHAR\s*\(MAX\)/gi, 'TEXT'],
        [/\bNVARCHAR\s*\((\d+)\)/gi, 'VARCHAR($1)'],
        [/\bNCHAR\s*\((\d+)\)/gi, 'CHAR($1)'],
        [/\bDATETIME2(?:\s*\(\d+\))?/gi, 'TIMESTAMP'],
        [/\bDATETIME\b/gi, 'TIMESTAMP'],
        [/\bSMALLDATETIME\b/gi, 'TIMESTAMP'],
        [/\bDATETIMEOFFSET(?:\s*\(\d+\))?/gi, 'TIMESTAMPTZ'],
        [/\bBIT\b/gi, 'BOOLEAN'],
        [/\bMONEY\b/gi, 'NUMERIC(19,4)'],
        [/\bSMALLMONEY\b/gi, 'NUMERIC(10,4)'],
        [/\bUNIQUEIDENTIFIER\b/gi, 'UUID'],
        [/\bVARBINARY\s*\((?:MAX|\d+)\)/gi, 'BYTEA'],
        [/\bBINARY\s*\(\d+\)/gi, 'BYTEA'],
        [/\bIMAGE\b/gi, 'BYTEA'],
        [/\bNTEXT\b/gi, 'TEXT'],
        [/\bXML\b/gi, 'TEXT'],
        [/\bHIERARCHYID\b/gi, 'VARCHAR(4000)'],
        [/\bTINYINT\b/gi, 'SMALLINT'],
    ];

    let converted = false;
    mappings.forEach(([regex, replacement]) => {
        if (regex.test(sql)) {
            converted = true;
            sql = sql.replace(regex, replacement);
        }
    });

    if (converted) {
        changes.push({ type: 'modified', message: 'Converted SQL Server data types to PostgreSQL equivalents' });
    }
    return sql;
}

function removeClusteredKeywords(sql, changes) {
    const regex = /\b(?:NON)?CLUSTERED\s*/gi;
    if (regex.test(sql)) {
        changes.push({ type: 'removed', message: 'Removed CLUSTERED/NONCLUSTERED keywords' });
        sql = sql.replace(regex, '');
    }
    return sql;
}

function removeFilegroups(sql, changes) {
    const regex = /\s+ON\s+["[]?\w+["\]]?(?=\s*$)/gim;
    const textImageRegex = /\s+TEXTIMAGE_ON\s+["[]?\w+["\]]?/gi;

    let removed = false;
    if (regex.test(sql)) {
        sql = sql.replace(regex, '');
        removed = true;
    }
    if (textImageRegex.test(sql)) {
        sql = sql.replace(textImageRegex, '');
        removed = true;
    }

    if (removed) {
        changes.push({ type: 'removed', message: 'Removed filegroup placement clauses (ON [PRIMARY], TEXTIMAGE_ON)' });
    }
    return sql;
}

function removeWithOptions(sql, changes) {
    const withRegex = /\s+WITH\s*\(\s*(?:PAD_INDEX|FILLFACTOR|STATISTICS_NORECOMPUTE|IGNORE_DUP_KEY|ALLOW_ROW_LOCKS|ALLOW_PAGE_LOCKS|OPTIMIZE_FOR_SEQUENTIAL_KEY|DATA_COMPRESSION)\s*=\s*[^)]*\)/gi;
    if (withRegex.test(sql)) {
        changes.push({ type: 'removed', message: 'Removed WITH (index/table options) clauses' });
        sql = sql.replace(withRegex, '');
    }
    return sql;
}

function removeTsqlProcedures(sql, changes) {
    const procRegex = /CREATE\s+(?:OR\s+ALTER\s+)?(?:PROCEDURE|PROC)\s+([\w."]+)[^]*?(?:^GO\s*$|(?=CREATE\s))/gim;
    const matches = sql.match(procRegex);
    if (matches) {
        matches.forEach(m => {
            const name = m.match(/(?:PROCEDURE|PROC)\s+([\w."]+)/i);
            changes.push({ type: 'removed', message: `Removed stored procedure "${name ? name[1] : 'unknown'}" — not supported in DSQL` });
        });
        sql = sql.replace(procRegex, '');
    }

    const funcRegex = /CREATE\s+(?:OR\s+ALTER\s+)?FUNCTION\s+([\w."]+)[^]*?(?:^GO\s*$|(?=CREATE\s))/gim;
    const funcMatches = sql.match(funcRegex);
    if (funcMatches) {
        funcMatches.forEach(m => {
            const name = m.match(/FUNCTION\s+([\w."]+)/i);
            changes.push({ type: 'removed', message: `Removed T-SQL function "${name ? name[1] : 'unknown'}"` });
        });
        sql = sql.replace(funcRegex, '');
    }

    return sql;
}

function convertGetdate(sql, changes) {
    const regex = /\bGETDATE\s*\(\s*\)/gi;
    if (regex.test(sql)) {
        changes.push({ type: 'modified', message: 'Converted GETDATE() to NOW()' });
        sql = sql.replace(regex, 'NOW()');
    }
    const utcRegex = /\bGETUTCDATE\s*\(\s*\)/gi;
    if (utcRegex.test(sql)) {
        sql = sql.replace(utcRegex, 'NOW()');
    }
    return sql;
}

function convertIsnull(sql, changes) {
    const regex = /\bISNULL\s*\(/gi;
    if (regex.test(sql)) {
        changes.push({ type: 'modified', message: 'Converted ISNULL() to COALESCE()' });
        sql = sql.replace(/\bISNULL\s*\(/gi, 'COALESCE(');
    }
    return sql;
}

function removeSchemaBinding(sql, changes) {
    const regex = /\s+WITH\s+SCHEMABINDING/gi;
    if (regex.test(sql)) {
        changes.push({ type: 'removed', message: 'Removed WITH SCHEMABINDING' });
        sql = sql.replace(regex, '');
    }
    return sql;
}
