"""
Aurora DSQL Schema Converter — Lambda Handler.
Routes between:
  - /convert: Strands Agent + Bedrock Claude for AI-powered conversion
  - /lint: dsql-lint binary for offline validation and auto-fix
"""

import json
from typing import Any, Dict
from strands import Agent
from strands.models import BedrockModel
from lint_handler import handle_lint

SYSTEM_PROMPT = """You are an expert database engineer specializing in Aurora DSQL migrations.
Your task is to convert PostgreSQL DDL schemas into Aurora DSQL-compatible schemas.

Aurora DSQL SUPPORTS the following (keep or convert to these):
- Sequences: CREATE SEQUENCE is supported but REQUIRES explicit CACHE (must be 1 or >= 65536). Add CACHE 1 if missing. Fix invalid CACHE values (2-65535) to 65536.
- Identity columns: GENERATED ALWAYS/BY DEFAULT AS IDENTITY is supported. Ensure the sequence options include CACHE 1 or CACHE >= 65536.
- SERIAL/BIGSERIAL: Convert to BIGINT GENERATED BY DEFAULT AS IDENTITY (CACHE 1).
- SQL functions: CREATE FUNCTION with LANGUAGE SQL is supported. Keep these.
- nextval(), currval(), setval(): Supported for use with sequences.
- Standard DDL: CREATE TABLE, CREATE INDEX ASYNC, CREATE VIEW, CHECK constraints, UNIQUE, NOT NULL, DEFAULT, standard data types.
- UUID and gen_random_uuid(): Supported natively.

Aurora DSQL does NOT support — you MUST handle these:
1. FOREIGN KEY constraints — Remove all REFERENCES, FOREIGN KEY clauses, and FK constraints. Add a comment noting referential integrity must be enforced at the application layer.
2. TRIGGERS — Remove all CREATE TRIGGER statements. Note in comments what the trigger did.
3. PL/pgSQL functions/procedures — Remove CREATE FUNCTION/PROCEDURE blocks that use LANGUAGE plpgsql. Note in comments what they did. Suggest rewriting as LANGUAGE SQL if simple, otherwise move to application layer.
4. EXTENSIONS — Remove all CREATE EXTENSION statements.
5. TABLE INHERITANCE — Remove INHERITS clauses.
6. PARTITIONING — Remove PARTITION BY clauses. DSQL distributes data automatically.
7. RULES — Remove CREATE RULE statements.
8. LISTEN/NOTIFY — Remove these statements.
9. TABLESPACE — Remove TABLESPACE clauses.
10. TEMPORARY TABLES — Convert to regular tables or CTEs.
11. CREATE INDEX — Convert to CREATE INDEX ASYNC (DSQL uses async index creation).

Output format:
1. First, output the converted SQL enclosed in ```sql ... ``` code block.
2. Then output a "## Changes Made" section with a bullet list of every modification, categorized as:
   - [REMOVED] — for features that were deleted
   - [MODIFIED] — for features that were transformed
   - [NOTE] — for important migration considerations

Keep all valid PostgreSQL syntax that IS supported by DSQL.

Preserve formatting and comments from the original where they remain relevant."""


def create_agent() -> Agent:
    model = BedrockModel(
        model_id="anthropic.claude-sonnet-4-20250514-v1:0",
        region_name="us-west-2",
        temperature=0.1,
        max_tokens=8192,
    )

    return Agent(
        model=model,
        system_prompt=SYSTEM_PROMPT,
        callback_handler=None,
    )


def handler(event: Dict[str, Any], _context) -> Dict[str, Any]:
    """Lambda handler that routes to convert or lint based on API path."""

    path = event.get("path", "") or event.get("resource", "")

    if "/lint" in path:
        return handle_lint(event)

    # Handle API Gateway proxy integration
    if "body" in event:
        body = json.loads(event["body"]) if isinstance(event["body"], str) else event["body"]
    else:
        body = event

    input_schema = body.get("schema", "")

    if not input_schema.strip():
        return {
            "statusCode": 400,
            "headers": cors_headers(),
            "body": json.dumps({"error": "No schema provided"}),
        }

    agent = create_agent()
    prompt = f"Convert the following PostgreSQL schema to be Aurora DSQL-compatible:\n\n```sql\n{input_schema}\n```"

    result = agent(prompt)
    response_text = str(result)

    sql_output, changes = parse_response(response_text)

    return {
        "statusCode": 200,
        "headers": cors_headers(),
        "body": json.dumps({
            "converted_schema": sql_output,
            "changes": changes,
            "raw_response": response_text,
        }),
    }


def parse_response(text: str) -> tuple[str, list[dict]]:
    """Extract SQL and change list from the agent's response."""
    sql = ""
    changes = []

    # Extract SQL from code block
    if "```sql" in text:
        parts = text.split("```sql")
        if len(parts) > 1:
            sql_block = parts[1].split("```")[0]
            sql = sql_block.strip()
    elif "```" in text:
        parts = text.split("```")
        if len(parts) > 1:
            sql = parts[1].strip()

    # Extract changes
    if "## Changes Made" in text:
        changes_section = text.split("## Changes Made")[1]
        for line in changes_section.split("\n"):
            line = line.strip()
            if line.startswith("- [REMOVED]") or line.startswith("- **[REMOVED]"):
                changes.append({"type": "removed", "message": clean_change(line, "REMOVED")})
            elif line.startswith("- [MODIFIED]") or line.startswith("- **[MODIFIED]"):
                changes.append({"type": "modified", "message": clean_change(line, "MODIFIED")})
            elif line.startswith("- [NOTE]") or line.startswith("- **[NOTE]"):
                changes.append({"type": "info", "message": clean_change(line, "NOTE")})

    if not sql:
        sql = text

    return sql, changes


def clean_change(line: str, tag: str) -> str:
    """Remove the tag prefix from a change line."""
    line = line.lstrip("- ")
    line = line.replace(f"[{tag}]", "").replace(f"**[{tag}]**", "")
    return line.strip().lstrip("— ").lstrip("- ").strip()


def cors_headers() -> dict:
    return {
        "Content-Type": "application/json",
        "Access-Control-Allow-Origin": "*",
        "Access-Control-Allow-Headers": "Content-Type",
        "Access-Control-Allow-Methods": "POST, OPTIONS",
    }
